//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace ZG69.Model
{

	/// <summary>
	/// 实体类T_leavewords 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("T_leavewords")]
	[Serializable]
	public partial class T_leavewords : Entity 
	{
		#region Model
		private int _ID;
		private string _Title;
		private string _Content;
		private string _Username;
		private string _UserEmail;
		private string _UserPhone;
		private string _UserCity;
		private string _UserIP;
		private string _LeaveDate;
		private string _IsAnswer;
		private string _AnswerContent;
		private string _AnswerUser;
		private string _AnswerDate;
		private string _AnswerPhone;
		private string _AnswerCity;
		private string _AnswerIP;
		/// <summary>
		/// 
		/// </summary>
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Username
		{
			get{ return _Username; }
			set
			{
				this.OnPropertyValueChange(_.Username,_Username,value);
				this._Username=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserEmail
		{
			get{ return _UserEmail; }
			set
			{
				this.OnPropertyValueChange(_.UserEmail,_UserEmail,value);
				this._UserEmail=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserPhone
		{
			get{ return _UserPhone; }
			set
			{
				this.OnPropertyValueChange(_.UserPhone,_UserPhone,value);
				this._UserPhone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserCity
		{
			get{ return _UserCity; }
			set
			{
				this.OnPropertyValueChange(_.UserCity,_UserCity,value);
				this._UserCity=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UserIP
		{
			get{ return _UserIP; }
			set
			{
				this.OnPropertyValueChange(_.UserIP,_UserIP,value);
				this._UserIP=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LeaveDate
		{
			get{ return _LeaveDate; }
			set
			{
				this.OnPropertyValueChange(_.LeaveDate,_LeaveDate,value);
				this._LeaveDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IsAnswer
		{
			get{ return _IsAnswer; }
			set
			{
				this.OnPropertyValueChange(_.IsAnswer,_IsAnswer,value);
				this._IsAnswer=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AnswerContent
		{
			get{ return _AnswerContent; }
			set
			{
				this.OnPropertyValueChange(_.AnswerContent,_AnswerContent,value);
				this._AnswerContent=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AnswerUser
		{
			get{ return _AnswerUser; }
			set
			{
				this.OnPropertyValueChange(_.AnswerUser,_AnswerUser,value);
				this._AnswerUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AnswerDate
		{
			get{ return _AnswerDate; }
			set
			{
				this.OnPropertyValueChange(_.AnswerDate,_AnswerDate,value);
				this._AnswerDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AnswerPhone
		{
			get{ return _AnswerPhone; }
			set
			{
				this.OnPropertyValueChange(_.AnswerPhone,_AnswerPhone,value);
				this._AnswerPhone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AnswerCity
		{
			get{ return _AnswerCity; }
			set
			{
				this.OnPropertyValueChange(_.AnswerCity,_AnswerCity,value);
				this._AnswerCity=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AnswerIP
		{
			get{ return _AnswerIP; }
			set
			{
				this.OnPropertyValueChange(_.AnswerIP,_AnswerIP,value);
				this._AnswerIP=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Title,
				_.Content,
				_.Username,
				_.UserEmail,
				_.UserPhone,
				_.UserCity,
				_.UserIP,
				_.LeaveDate,
				_.IsAnswer,
				_.AnswerContent,
				_.AnswerUser,
				_.AnswerDate,
				_.AnswerPhone,
				_.AnswerCity,
				_.AnswerIP};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Title,
				this._Content,
				this._Username,
				this._UserEmail,
				this._UserPhone,
				this._UserCity,
				this._UserIP,
				this._LeaveDate,
				this._IsAnswer,
				this._AnswerContent,
				this._AnswerUser,
				this._AnswerDate,
				this._AnswerPhone,
				this._AnswerCity,
				this._AnswerIP};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","T_leavewords");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","T_leavewords","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","T_leavewords","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content","T_leavewords","Content");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Username = new Field("Username","T_leavewords","Username");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserEmail = new Field("UserEmail","T_leavewords","UserEmail");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserPhone = new Field("UserPhone","T_leavewords","UserPhone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserCity = new Field("UserCity","T_leavewords","UserCity");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserIP = new Field("UserIP","T_leavewords","UserIP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LeaveDate = new Field("LeaveDate","T_leavewords","LeaveDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsAnswer = new Field("IsAnswer","T_leavewords","IsAnswer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AnswerContent = new Field("AnswerContent","T_leavewords","AnswerContent");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AnswerUser = new Field("AnswerUser","T_leavewords","AnswerUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AnswerDate = new Field("AnswerDate","T_leavewords","AnswerDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AnswerPhone = new Field("AnswerPhone","T_leavewords","AnswerPhone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AnswerCity = new Field("AnswerCity","T_leavewords","AnswerCity");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AnswerIP = new Field("AnswerIP","T_leavewords","AnswerIP");
		}
		#endregion


	}
}

