//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace ZG69.Model
{

	/// <summary>
	/// 实体类T_users 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("T_users")]
	[Serializable]
	public partial class T_users : Entity 
	{
		#region Model
		private int _id;
		private string _name;
		private string _pwd;
		private string _regtime;
		private int? _state;
		private string _tel;
		private string _email;
		private int? _online;
		private string _lastlogintime;
		private string _address;
		/// <summary>
		/// 
		/// </summary>
		public int id
		{
			get{ return _id; }
			set
			{
				this.OnPropertyValueChange(_.id,_id,value);
				this._id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string name
		{
			get{ return _name; }
			set
			{
				this.OnPropertyValueChange(_.name,_name,value);
				this._name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string pwd
		{
			get{ return _pwd; }
			set
			{
				this.OnPropertyValueChange(_.pwd,_pwd,value);
				this._pwd=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string regtime
		{
			get{ return _regtime; }
			set
			{
				this.OnPropertyValueChange(_.regtime,_regtime,value);
				this._regtime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? state
		{
			get{ return _state; }
			set
			{
				this.OnPropertyValueChange(_.state,_state,value);
				this._state=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string tel
		{
			get{ return _tel; }
			set
			{
				this.OnPropertyValueChange(_.tel,_tel,value);
				this._tel=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string email
		{
			get{ return _email; }
			set
			{
				this.OnPropertyValueChange(_.email,_email,value);
				this._email=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? online
		{
			get{ return _online; }
			set
			{
				this.OnPropertyValueChange(_.online,_online,value);
				this._online=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string lastlogintime
		{
			get{ return _lastlogintime; }
			set
			{
				this.OnPropertyValueChange(_.lastlogintime,_lastlogintime,value);
				this._lastlogintime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string address
		{
			get{ return _address; }
			set
			{
				this.OnPropertyValueChange(_.address,_address,value);
				this._address=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.id,
				_.name,
				_.pwd,
				_.regtime,
				_.state,
				_.tel,
				_.email,
				_.online,
				_.lastlogintime,
				_.address};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._id,
				this._name,
				this._pwd,
				this._regtime,
				this._state,
				this._tel,
				this._email,
				this._online,
				this._lastlogintime,
				this._address};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","T_users");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id","T_users","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field name = new Field("name","T_users","name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field pwd = new Field("pwd","T_users","pwd");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field regtime = new Field("regtime","T_users","regtime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field state = new Field("state","T_users","state");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field tel = new Field("tel","T_users","tel");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field email = new Field("email","T_users","email");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field online = new Field("online","T_users","online");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field lastlogintime = new Field("lastlogintime","T_users","lastlogintime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field address = new Field("address","T_users","address");
		}
		#endregion


	}
}

